<a href="https://colab.research.google.com/github/aneeshmurali-n/Python-Tasks/blob/main/TASK7_Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy

##1. How to extract all odd numbers from arr?


In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#print(arr % 2 == 1) #base logic
#We re using arr % 2 == 1 to create a boolean mask where True represents positions in the array where the corresponding element is odd, and then using this mask to filter the elements of arr.
odd_numbers = arr[arr % 2 == 1] # Use boolean indexing to extract odd numbers
print(odd_numbers)


[1 3 5 7 9]


##2. Replace all odd numbers in arr with -1 without changing

In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1 # Replace all odd numbers with -1
print(arr) # Print the modified array

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


##3.  Convert a 1D array to a 2D array with 2 rows
<p>Desired Output:<br>
array([[0, 1, 2, 3, 4],<br>
        [5, 6, 7, 8, 9]])</p>


In [ ]:
import numpy as np
arr = np.arange(10)  # 1D array with numbers from 0 to 9
# Reshape the 1D array to a 2D array with 2 rows
array_2d = arr.reshape(2, -1)
#2 indicates the number of rows you want in the reshaped array.
#-1, is a placeholder. When -1 is used in the reshape() method,
#it means that NumPy should automatically determine the number of columns based on the size of the array and the specified number of rows.
print(array_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


##4. Stack arrays a and b vertically
<p>Desired Output:<br>
 array([[0, 1, 2, 3, 4],<br>
        [5, 6, 7, 8, 9],<br>
        [1, 1, 1, 1, 1],<br>
        [1, 1, 1, 1, 1]])</p>

In [ ]:
import numpy as np
a = np.arange(10).reshape(2, -1)  # Create a 2D array 'a' with numbers from 0 to 9, reshaped to have 2 rows
#print(a,end = '\n\n')
b = np.repeat(1, 10).reshape(2, -1)  # Create a 2D array 'b' with all elements as 1, reshaped to have 2 rows
#print(b,end = '\n\n')
arr_stack_a_b = np.vstack((a, b)) # Stack arrays 'a' and 'b' vertically, def vstack(tup, *, dtype=None, casting='same_kind')
print(arr_stack_a_b) # print vertically stacked array


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


##5. Stack the arrays a and b horizontally.
<p>Desired Output:<br>
 array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],<br>
        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])</p>

In [ ]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
# Stack arrays 'a' and 'b' horizontally
arr_stack_a_b = np.hstack((a, b)) #def hstack(tup, *, dtype=None, casting='same_kind')
print(arr_stack_a_b) # print horizontally stacked array

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


##6.How to get the common items between two python numpy arrays?
Get the common items between a and b



In [ ]:
import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
# Use the np.intersect1d function to find the common items between arrays a and b
# This function returns the sorted, unique values that are in both of the input arrays
c = np.intersect1d(a, b) #def intersect1d(ar1, ar2, assume_unique=False, return_indices=False)
# Print the common items
print(c)


[2 4]


##7.How to remove from one array those items that exist in another?
Q. From array a remove all items present in array b

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

# Use the np.setdiff1d function to find the items in a that are not in b
# This function returns the sorted, unique values in a that are not in b
a = np.setdiff1d(a, b) # Remove items in b from a
print(a) # Print array a

[1 2 3 4]


##8. How to get the positions where elements of two arrays match?

Q. Get the positions where elements of a and b match
<p>Desired Output:<br>
(array([1, 3, 5, 7]),)</p>

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Use np.where to find the positions where elements of a and b match
matched = np.where(a == b)
# Print the matching positions
print(matched)

(array([1, 3, 5, 7]),)


##9. How to extract all numbers between a given range from a numpy array?
Get all items between 5 and 10 from a
<p>Desired Output:<br>
(array([6, 9, 10]),)</p>

In [ ]:
import numpy as np

a = np.array([2, 6, 1, 9, 10, 3, 27])

# Use boolean indexing to get all items between 5 and 10
items_5_to_10 = a[(a >= 5) & (a <= 10)]
# Print items between 5 and 10 from a
print(items_5_to_10)

[ 6  9 10]


#Pandas

##Pandas Data Series

##1. Write a Pandas program to convert a dictionary to a Pandas series.

```
Sample Series:
Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64

```

In [ ]:
import pandas as pd #Import the Pandas library

#original dictionary
data = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
# pd.Series(data) function converts the dictionary data into a Pandas series.
# The keys of the dictionary become the index of the series, and the values of the dictionary become the values of the series.
# Print the converted series
print(f"Converted series:\n{pd.Series(data)}")


Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


##2. Write a Pandas program to convert a NumPy array to a Pandas series.
```
Sample Series:
  NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

```

In [ ]:
import numpy as np
import pandas as pd

# NumPy array
numpy_array = np.array([10, 20, 30, 40, 50])

# Convert the NumPy array to a Pandas series
pandas_series = pd.Series(numpy_array)

# Print the original NumPy array and the converted Pandas series
print(f"NumPy array:\n{numpy_array}\nConverted Pandas series:\n{pandas_series}")


NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


##3. Write a Pandas program to change the data type of given a column or a Series.

```
Sample Series:
    Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

```

In [ ]:
import pandas as pd

# Define the original data series
data_series = pd.Series([100, 200, 'python', 300.12, 400])

# Print the original data series
print(f"Original Data Series:\n{data_series}\n")

# Change the data type to numeric, coercing errors to NaN
numeric_series = pd.to_numeric(data_series, errors='coerce')

# Print the converted series
print(f"Change the said data type to numeric:\n{numeric_series}")


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64


##4. Write a Pandas program to convert the first column of a DataFrame as a Series.

```
Sample Output:  
Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

1st column as a Series:
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>

```

In [ ]:
import pandas as pd

# Create the original DataFrame
data = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1, 11]} # a dictionary 'data' with three keys: 'col1', 'col2', and 'col3'.
                                                                                               # Each key has a list of values that will form the columns of the DataFrame.

df = pd.DataFrame(data)                     # pd.DataFrame(data) function converts the dictionary into a DataFrame named df.

# Print the original DataFrame
print(f"Original DataFrame\n{df}\n")

# Convert the first column to a Series
first_column_series = df['col1']            # This accesses the column labeled 'col1' from the DataFrame df and assigns it to the variable first_column_series.
                                            # The resulting first_column_series is a Pandas Series containing the values of the first column.


# Print the first column as a Series
print(f"1st column as a Series:\n{first_column_series}\n{type(first_column_series)}")


Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

1st column as a Series:
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>


##5. Write a Pandas program to convert a given Series to an array.

```
Sample Output:
Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']
<class 'numpy.ndarray'>

```

In [ ]:
import pandas as pd

# Define the original data series
data_series = pd.Series(['100', '200', 'python', '300.12', '400'])

# Print the original data series
print(f"Original Data Series:\n{data_series}\n")

# Convert the Series to a NumPy array
np_array = data_series.to_numpy()                       # .to_numpy() method converts the Pandas series 'data_series' into a NumPy array.

# Print the converted array and its type
print(f"Series to an array\n{np_array}\n{type(np_array)}")

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Series to an array
['100' '200' 'python' '300.12' '400']
<class 'numpy.ndarray'>


##6 Write a Pandas program to convert Series of lists to one Series.
```
Sample Output:
Original Series of list
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object
One Series
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

```

In [ ]:
import pandas as pd
# Create a Series
series_of_lists = pd.Series([['Red', 'Green', 'White'],['Red', 'Black'],['Yellow']])

# Flatten the Series of lists into one Series using explode and reset_index
one_series = series_of_lists.explode().reset_index(drop=True) # explode() function to convert each element of the list-like objects in the Series into separate rows.
                                                                # reset_index(drop=True) to reset the index of the resulting Series so that it is sequential.
print(f"Original Series of list\n{series_of_lists}\n\nOne Series\n{one_series}")



Original Series of list
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

One Series
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object


##7.Write a Pandas program to sort a given Series.
```
Sample Output:
Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
0       100
1       200
3    300.12
4       400
2    python
dtype: object
```

In [ ]:
import pandas as pd

# Data Series
data = pd.Series([100, 200, 'python', 300.12, 400])

# Print original Data Series
print(f"Original Data Series:\n{data}\n")

# Sort the Data Series
sorted_data = data.astype(str).sort_values() #convert all elements in the Series to strings using astype(str) and then sort it with sort_values() methode

# Print sorted Data Series
print(f"Sorted Data Series:\n{sorted_data}")



Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Sorted Data Series:
0       100
1       200
3    300.12
4       400
2    python
dtype: object


##Pandas DataFrame

##1.Write a Pandas program to create a dataframe from a dictionary and display it.
```
Sample data: {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
Expected Output:
    X   Y   Z                                                         
0  78  84  86                                                        
1  85  94  97                                                         
2  96  89  96                                                      
3  80  83  72                                                         
4  86  86  83

```


In [ ]:
import pandas as pd

# Sample data
data = {'X': [78, 85, 96, 80, 86], 'Y': [84, 94, 89, 83, 86], 'Z': [86, 97, 96, 72, 83]}

# Create DataFrame
df = pd.DataFrame(data)

# Print DataFrame
print(df)


    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


##2. Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.
```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

```
Expected Output:
   attempts       name qualify  score                              
a         1  Anastasia     yes   12.5                                 
b         3       Dima      no    9.0                                 
....                              
i         2      Kevin      no    8.0                                
j         1      Jonas     yes   19.0

```

In [ ]:
import pandas as pd
import numpy as np

#Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(data = exam_data, index = labels)
# 'data = exam_data' This specifies the dictionary exam_data as the data to populate the DataFrame columns.
# 'index = labels' This specifies the list labels as the index labels for the DataFrame.
# Reorder columns as per the expected output
df = df.reindex(columns=['attempts', 'name', 'qualify', 'score'])

print(df)

   attempts       name qualify  score
a         1  Anastasia     yes   12.5
b         3       Dima      no    9.0
c         2  Katherine     yes   16.5
d         3      James      no    NaN
e         2      Emily      no    9.0
f         3    Michael     yes   20.0
g         1    Matthew     yes   14.5
h         1      Laura      no    NaN
i         2      Kevin      no    8.0
j         1      Jonas     yes   19.0


##3. Write a Pandas program to get the first 3 rows of a given DataFrame.
```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

```
Expected Output:
First three rows of the data frame:                                   
   attempts       name qualify  score                              
a         1  Anastasia     yes   12.5                                 
b         3       Dima      no    9.0                                 
c         2  Katherine     yes   16.5

```

In [ ]:
import pandas as pd
import numpy as np
#Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(data = exam_data, index = labels)
# 'data = exam_data' This specifies the dictionary exam_data as the data to populate the DataFrame columns.
# 'index = labels' This specifies the list labels as the index labels for the DataFrame.

# Reorder columns as per the expected output
df = df.reindex(columns=['attempts', 'name', 'qualify', 'score'])

print(f"First three rows of the data frame:\n{df.head(3)}") # The .head(3) method retrieves the first 3 rows of the DataFrame df.


First three rows of the data frame:
   attempts       name qualify  score
a         1  Anastasia     yes   12.5
b         3       Dima      no    9.0
c         2  Katherine     yes   16.5


##4.Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Select specific columns:                                               
        name  score                                                  
a  Anastasia   12.5                                                   
b       Dima    9.0                                                
c  Katherine   16.5                                                    
...                                                  
h      Laura    NaN                                                   
i      Kevin    8.0                                                  
j      Jonas   19.0
```

In [ ]:
import pandas as pd
import numpy as np
#Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(data = exam_data, index = labels)
# 'data = exam_data' This specifies the dictionary exam_data as the data to populate the DataFrame columns.
# 'index = labels' This specifies the list labels as the index labels for the DataFrame.


print(f"Select specific columns:\n{df[['name', 'score']]}") #The double square brackets [['name', 'score']] are used to specify a list of column names that we want to select from the DataFrame df.

Select specific columns:
        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


##5.  Write a Pandas program to select the specified columns and rows from a given data frame.
```
Sample Python dictionary data and list labels:
Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data frame.
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Select specific columns and rows:
   score qualify
b    9.0      no
d    NaN      no
f   20.0     yes
g   14.5     yes

```

In [ ]:
import pandas as pd
import numpy as np
#Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(data = exam_data, index = labels)
# 'data = exam_data' This specifies the dictionary exam_data as the data to populate the DataFrame columns.
# 'index = labels' This specifies the list labels as the index labels for the DataFrame.

# Select rows b,d,f,g and columns 'score' and 'qualify' and print output
# .loc, we can specify the row labels and column labels accordingly.
print(f"Select specific columns and rows:\n{df.loc[['b','d','f','g'], ['score', 'qualify']]}")

Select specific columns and rows:
   score qualify
b    9.0      no
d    NaN      no
f   20.0     yes
g   14.5     yes


##6. Write a Pandas program to select the rows where the number of attempts in the examination is greater than 2.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

```
Expected Output:
Number of attempts in the examination is greater than 2:
      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

```

In [ ]:
import pandas as pd
import numpy as np
#Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(data = exam_data, index = labels)
# 'data = exam_data' This specifies the dictionary exam_data as the data to populate the DataFrame columns.
# 'index = labels' This specifies the list labels as the index labels for the DataFrame.

# select the rows where the number of attempts in the examination is greater than 2.
print(f"Number of attempts in the examination is greater than 2:\n{df.loc[df['attempts'] > 2]}")

#df['attempts'] > 2 selects rows where the condition is True.
#df.loc[boolean_condition] selects rows based on the boolean condition and selects all columns by default (:).

Number of attempts in the examination is greater than 2:
      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes


##7. Write a Pandas program to select the rows where the score is missing, i.e. is NaN.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

```
Expected Output:
Rows where score is missing:
   attempts   name qualify  score
d         3  James      no    NaN
h         1  Laura      no    NaN

```

In [ ]:
import pandas as pd
import numpy as np
#Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(data = exam_data, index = labels)
# 'data = exam_data' This specifies the dictionary exam_data as the data to populate the DataFrame columns.
# 'index = labels' This specifies the list labels as the index labels for the DataFrame.

# Reorder columns as per the expected output
df = df.reindex(columns=['attempts', 'name', 'qualify', 'score'])

# select the rows where the score is missing, i.e. is NaN.
print(f"Rows where score is missing:\n{df.loc[df['score'].isna()]}")

Rows where score is missing:
   attempts   name qualify  score
d         3  James      no    NaN
h         1  Laura      no    NaN


##8. Write a Pandas program to select the rows the score is between 15 and 20 (inclusive).
```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Rows where score between 15 and 20 (inclusive):                        
   attempts       name qualify  score                                  
c         2  Katherine     yes   16.5                                
f         3    Michael     yes   20.0                                 
j         1      Jonas     yes   19.0
```


In [ ]:
import pandas as pd
import numpy as np
#Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(data = exam_data, index = labels)
# 'data = exam_data' This specifies the dictionary exam_data as the data to populate the DataFrame columns.
# 'index = labels' This specifies the list labels as the index labels for the DataFrame.

# Reorder columns as per the expected output
df = df.reindex(columns=['attempts', 'name', 'qualify', 'score'])

# select the rows the score is between 15 and 20 (inclusive).
print(f"Rows where score between 15 and 20 (inclusive):\n{df.loc[ (df['score'] >= 15) & (df['score'] <= 20) ]}")

Rows where score between 15 and 20 (inclusive):
   attempts       name qualify  score
c         2  Katherine     yes   16.5
f         3    Michael     yes   20.0
j         1      Jonas     yes   19.0


##9. Write a Pandas program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Number of attempts in the examination is less than 2 and score greater than 15 :
    name  score  attempts qualify
j  Jonas   19.0         1     yes

```

In [ ]:
import pandas as pd
import numpy as np
#Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(data = exam_data, index = labels)
# 'data = exam_data' This specifies the dictionary exam_data as the data to populate the DataFrame columns.
# 'index = labels' This specifies the list labels as the index labels for the DataFrame.

# select the rows where number of attempts in the examination is less than 2 and score greater than 15.
print(f"Number of attempts in the examination is less than 2 and score greater than 15 :\n{df.loc[ (df['attempts'] < 2) & (df['score'] > 15) ]}")

Number of attempts in the examination is less than 2 and score greater than 15 :
    name  score  attempts qualify
j  Jonas   19.0         1     yes


##10. Write a Pandas program to change the score in row 'd' to 11.5.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

```

```
Expected Output:
Change the score in row 'd' to 11.5:                                  
   attempts       name qualify  score                                
a         1  Anastasia     yes   12.5                               
b         3       Dima      no    9.0                                
c         2  Katherine     yes   16.5
...                                
i         2      Kevin      no    8.0                                 
j         1      Jonas     yes   19.0

```

In [ ]:
import pandas as pd
import numpy as np
#Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(data = exam_data, index = labels)
# 'data = exam_data' This specifies the dictionary exam_data as the data to populate the DataFrame columns.
# 'index = labels' This specifies the list labels as the index labels for the DataFrame.

# Reorder columns as per the expected output
df = df.reindex(columns=['attempts', 'name', 'qualify', 'score'])

# change the score in row 'd' to 11.5.
df.loc['d','score'] = 11.5
# Accessing a Specific Cell: df.loc['d', 'score'] allows you to access the cell in row 'd' and column 'score'.
# Modifying the Value: The assignment operation df.loc['d', 'score'] = 11.5 changes the value in that cell to 11.5.


print(f"Change the score in row 'd' to 11.5:\n{df}")

Change the score in row 'd' to 11.5:
   attempts       name qualify  score
a         1  Anastasia     yes   12.5
b         3       Dima      no    9.0
c         2  Katherine     yes   16.5
d         3      James      no   11.5
e         2      Emily      no    9.0
f         3    Michael     yes   20.0
g         1    Matthew     yes   14.5
h         1      Laura      no    NaN
i         2      Kevin      no    8.0
j         1      Jonas     yes   19.0


##11. Write a Pandas program to calculate the sum of the examination attempts by the students.
```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Sum of the examination attempts by the students:                     
19
```

In [ ]:
import pandas as pd
import numpy as np
#Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(data = exam_data, index = labels)
# 'data = exam_data' This specifies the dictionary exam_data as the data to populate the DataFrame columns.
# 'index = labels' This specifies the list labels as the index labels for the DataFrame.

#calculate the sum of the examination attempts by the students
print(f"Sum of the examination attempts by the students:\n{df['attempts'].sum()}")

Sum of the examination attempts by the students:
19


##12. Write a Pandas program to calculate the mean of all students' scores. Data is stored in a dataframe.
```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Mean score for each different student in data frame:                  
13.5625
```

In [ ]:
import pandas as pd
import numpy as np
#Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(data = exam_data, index = labels)
# 'data = exam_data' This specifies the dictionary exam_data as the data to populate the DataFrame columns.
# 'index = labels' This specifies the list labels as the index labels for the DataFrame.

#calculate the mean of all students' scores. Data is stored in a dataframe.
print(f"Mean score for each different student in data frame: \n{df['score'].mean()}")

Mean score for each different student in data frame: 
13.5625


##13. Write a Pandas program to replace the 'qualify' column contains the values 'yes' and 'no' with True and False.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

```
Expected Output:
Replace the 'qualify' column contains the values 'yes' and 'no'  with T
rue and  False:                                                      
   attempts       name  qualify  score                              
a         1  Anastasia     True   12.5                          
b         3       Dima    False    9.0                              
......                           
i         2      Kevin    False    8.0                                 
j         1      Jonas     True   19.0
```

In [ ]:
import pandas as pd
import numpy as np
#Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(data = exam_data, index = labels)
# 'data = exam_data' This specifies the dictionary exam_data as the data to populate the DataFrame columns.
# 'index = labels' This specifies the list labels as the index labels for the DataFrame.

# Reorder columns as per the expected output
df = df.reindex(columns=['attempts', 'name', 'qualify', 'score'])

#replace the 'qualify' column contains the values 'yes' and 'no' with True and False.
df['qualify'] = df['qualify'].replace({'yes':True, 'no':False})

print(f"Replace the 'qualify' column contains the values 'yes' and 'no'  with True and  False:\n{df}")

Replace the 'qualify' column contains the values 'yes' and 'no'  with True and  False:
   attempts       name  qualify  score
a         1  Anastasia     True   12.5
b         3       Dima    False    9.0
c         2  Katherine     True   16.5
d         3      James    False    NaN
e         2      Emily    False    9.0
f         3    Michael     True   20.0
g         1    Matthew     True   14.5
h         1      Laura    False    NaN
i         2      Kevin    False    8.0
j         1      Jonas     True   19.0


##14. Write a Pandas program to change the name 'James' to 'Suresh' in name column of the DataFrame.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Change the name 'James' to \?Suresh\?:                                
   attempts       name qualify  score                                  
a         1  Anastasia     yes   12.5                                  
b         3       Dima      no    9.0                                  
.......                               
i         2      Kevin      no    8.0                                 
j         1      Jonas     yes   19.0
```

In [ ]:
import pandas as pd
import numpy as np
#Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(data = exam_data, index = labels)
# 'data = exam_data' This specifies the dictionary exam_data as the data to populate the DataFrame columns.
# 'index = labels' This specifies the list labels as the index labels for the DataFrame.

# Reorder columns as per the expected output
df = df.reindex(columns=['attempts', 'name', 'qualify', 'score'])

#change the name 'James' to 'Suresh' in name column of the DataFrame.
df['name'] = df['name'].replace('James','Suresh')


print(f"Change the name 'James' to \?Suresh\?:\n{df}")

Change the name 'James' to \?Suresh\?:
   attempts       name qualify  score
a         1  Anastasia     yes   12.5
b         3       Dima      no    9.0
c         2  Katherine     yes   16.5
d         3     Suresh      no    NaN
e         2      Emily      no    9.0
f         3    Michael     yes   20.0
g         1    Matthew     yes   14.5
h         1      Laura      no    NaN
i         2      Kevin      no    8.0
j         1      Jonas     yes   19.0


##15. Write a Pandas program to delete the 'attempts' column from the DataFrame.
```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Delete the 'attempts' column from the data frame:                    
        name qualify  score                                          
a  Anastasia     yes   12.5                                           
b       Dima      no    9.0                                          
.....                                       
i      Kevin      no    8.0                                          
j      Jonas     yes   19.0
```

In [ ]:
import pandas as pd
import numpy as np
#Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(data = exam_data, index = labels)
# 'data = exam_data' This specifies the dictionary exam_data as the data to populate the DataFrame columns.
# 'index = labels' This specifies the list labels as the index labels for the DataFrame.

# Reorder columns as per the expected output
df = df.reindex(columns=['attempts', 'name', 'qualify', 'score'])

#delete the 'attempts' column from the DataFrame.
df = df.drop(columns='attempts')
print(f"Delete the 'attempts' column from the data frame:\n{df}")

Delete the 'attempts' column from the data frame:
        name qualify  score
a  Anastasia     yes   12.5
b       Dima      no    9.0
c  Katherine     yes   16.5
d      James      no    NaN
e      Emily      no    9.0
f    Michael     yes   20.0
g    Matthew     yes   14.5
h      Laura      no    NaN
i      Kevin      no    8.0
j      Jonas     yes   19.0


##16.  Write a Pandas program to insert a new column in existing DataFrame.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
New DataFrame after inserting the 'color' column                       
   attempts       name qualify  score   color                       
a         1  Anastasia     yes   12.5     Red                         
b         3       Dima      no    9.0    Blue                        
.......                     
i         2      Kevin      no    8.0   Green                        
j         1      Jonas     yes   19.0     Red
```

In [ ]:
import pandas as pd
import numpy as np
#Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(data = exam_data, index = labels)
# 'data = exam_data' This specifies the dictionary exam_data as the data to populate the DataFrame columns.
# 'index = labels' This specifies the list labels as the index labels for the DataFrame.

# Reorder columns as per the expected output
df = df.reindex(columns=['attempts', 'name', 'qualify', 'score'])

# Define a new column 'color'
df['color'] = ['Red', 'Blue', 'Green', 'Yellow', 'Orange', 'Purple', 'Pink', 'Black', 'Green', 'Red']  # Assigning a list of colors as values to the new column 'color'

print(f"New DataFrame after inserting the 'color' column\n{df}")

New DataFrame after inserting the 'color' column
   attempts       name qualify  score   color
a         1  Anastasia     yes   12.5     Red
b         3       Dima      no    9.0    Blue
c         2  Katherine     yes   16.5   Green
d         3      James      no    NaN  Yellow
e         2      Emily      no    9.0  Orange
f         3    Michael     yes   20.0  Purple
g         1    Matthew     yes   14.5    Pink
h         1      Laura      no    NaN   Black
i         2      Kevin      no    8.0   Green
j         1      Jonas     yes   19.0     Red


##17.  Write a Pandas program to rename columns of a given DataFrame

```
Sample data:
Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9
New DataFrame after renaming columns:
   Column1  Column2  Column3
0        1        4        7
1        2        5        8
2        3        6        9
```

In [ ]:
import pandas as pd
#sample data dict
sample_data = {'col1':[1,2,3], 'col2':[4,5,6], 'col3':[7,8,9]}

# Create DataFrame
df = pd.DataFrame(sample_data)

#print original DataFrame
print(f"Original DataFrame\n{df}\n")

#rename columns of a given DataFrame
df = df.rename(columns = {'col1':'Column1', 'col2':'Column2', 'col3':'Column3'})

#print new dataFrame after renaming columns
print(f"New DataFrame after renaming columns:\n{df}")

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9

New DataFrame after renaming columns:
   Column1  Column2  Column3
0        1        4        7
1        2        5        8
2        3        6        9


##18. Write a Pandas program to select rows from a given DataFrame based on values in some columns.
```
Sample data:
Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
Rows for colum1 value == 4
   col1  col2  col3
1     4     5     8
3     4     7     0
```

In [ ]:
import pandas as pd
#sample data dict
sample_data = {'col1':[1,4,3,4,5], 'col2':[4,5,6,7,8], 'col3':[7,8,9,0,1]}

# Create DataFrame
df = pd.DataFrame(sample_data)

#print original DataFrame
print(f"Original DataFrame\n{df}\n")

#select rows from a given DataFrame based on values in some columns.
#Rows for colum1 value == 4
print(f"Rows for colum1 value == 4\n{df.loc[df['col1'] == 4]}")

Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1

Rows for colum1 value == 4
   col1  col2  col3
1     4     5     8
3     4     7     0


##19. Write a Pandas program to add one row in an existing DataFrame.

```
Sample data:
Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
After add one row:
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
5    10    11    12
```

In [ ]:
import pandas as pd

# Sample data
data = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}

# Create DataFrame
df = pd.DataFrame(data)

# Print original DataFrame
print(f"Original DataFrame:\n{df}\n")

# Add new row values 10, 11, 12 at the index position specified by len(df).
# the len(df) returns the current number of rows in the DataFrame which is 5
df.loc[len(df)] = [10, 11, 12] # add new row at index 5

# DataFrame after adding new row
print(f"After add one row:\n{df}")



Original DataFrame:
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1

After add one row:
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
5    10    11    12


##20. Write a Pandas program to replace all the NaN values with Zero's in a column of a dataframe.

```
Sample data:
Original DataFrame

   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
.....
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0

```
```

New DataFrame replacing all NaN with 0:
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
.....
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0
```

In [ ]:
import pandas as pd
import numpy as np
#Sample dictionary data
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}


# Create DataFrame
df = pd.DataFrame(data = exam_data)
# 'data = exam_data' This specifies the dictionary exam_data as the data to populate the DataFrame columns.

# Reorder columns as per the expected output
df = df.reindex(columns=['attempts', 'name', 'qualify', 'score'])

# print Original DataFrame
print(f"Original DataFrame\n{df}\n")

# replace NaN values with 0 in the 'score' column
df['score'] = df['score'].fillna(0)

# print New DataFrame replacing all NaN with 0:
print(f"New DataFrame replacing all NaN with 0:\n{df}")

Original DataFrame
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
3         3      James      no    NaN
4         2      Emily      no    9.0
5         3    Michael     yes   20.0
6         1    Matthew     yes   14.5
7         1      Laura      no    NaN
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0

New DataFrame replacing all NaN with 0:
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
3         3      James      no    0.0
4         2      Emily      no    9.0
5         3    Michael     yes   20.0
6         1    Matthew     yes   14.5
7         1      Laura      no    0.0
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0


##21. Write a Pandas program to count the NaN values in one or more columns in DataFrame.
```
Sample data:
Original DataFrame
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
3         3      James      no    NaN
4         2      Emily      no    9.0
5         3    Michael     yes   20.0
6         1    Matthew     yes   14.5
7         1      Laura      no    NaN
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0

Number of NaN values in one or more columns:
2

```

In [ ]:
import pandas as pd
import numpy as np
#Sample dictionary data
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}


# Create DataFrame
df = pd.DataFrame(data = exam_data)
# 'data = exam_data' This specifies the dictionary exam_data as the data to populate the DataFrame columns.

# Reorder columns as per the expected output
df = df.reindex(columns=['attempts', 'name', 'qualify', 'score'])

# print Original DataFrame
print(f"Original DataFrame\n{df}\n")

# print Number of NaN values in one or more columns:
print(f"Number of NaN values in one or more columns:\n{df.isna().sum().sum()}")

# When we call .sum() on the DataFrame resulting from df.isna(), it sums up the boolean values (True is treated as 1 and False as 0) along the columns (axis=0 by default).
# This gives you a Series where each value is the count of NaN values in each column.
# attempts    0
# name        0
# qualify     0
# score       2
# dtype: int64
# (Second .sum()):This .sum() is called on the Series resulting from the first .sum().
# It sums up all the values in the Series, which gives the total number of NaN values in the entire DataFrame.

Original DataFrame
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
3         3      James      no    NaN
4         2      Emily      no    9.0
5         3    Michael     yes   20.0
6         1    Matthew     yes   14.5
7         1      Laura      no    NaN
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0

Number of NaN values in one or more columns:
2


##22. Write a Pandas program to drop a list of rows from a specified DataFrame.
```
Sample data:
Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1


New DataFrame after removing 2nd & 4th rows:
   col1  col2  col3
0     1     4     7
1     4     5     8
3     4     7     0
```

In [ ]:
import pandas as pd

# Sample data
data = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}

# Create DataFrame
df = pd.DataFrame(data)

# Print original DataFrame
print(f"Original DataFrame:\n{df}\n")

# drop a list of rows from a specified DataFrame. drop index 2 and 4
new_df = df.drop([2,4])

# print New DataFrame after removing 2nd & 4th rows:
print(f"print New DataFrame after removing 2nd & 4th rows:\n{new_df}\n")

Original DataFrame:
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1

print New DataFrame after removing 2nd & 4th rows:
   col1  col2  col3
0     1     4     7
1     4     5     8
3     4     7     0



##23. . Write a Pandas program to convert DataFrame column type from string to datetime.

```

Sample data:
String Date:
0    3/11/2000
1    3/12/2000
2    3/13/2000
dtype: object


Original DataFrame (string to datetime):
           0
0 2000-03-11
1 2000-03-12
2 2000-03-13
```

In [ ]:
import pandas as pd

# Sample data as a pandas Series
pd_series = pd.Series(['3/11/2000', '3/12/2000', '3/13/2000'])

# Print original Series
print(f"String Date:\n{pd_series}\n")

# Convert the Series to a DataFrame
df = pd.DataFrame(pd_series)

# Convert the column to datetime
df[0] = pd.to_datetime(df[0])   # df[0] is passed as an argument to pd.to_datetime(), which means the entire column 0 of the DataFrame is being converted from strings to datetime objects.


# Print DataFrame after conversion
print(f"Original DataFrame (string to datetime):\n{df}")


String Date:
0    3/11/2000
1    3/12/2000
2    3/13/2000
dtype: object

Original DataFrame (string to datetime):
           0
0 2000-03-11
1 2000-03-12
2 2000-03-13


##24. Write a Pandas program to find the row for where the value of a given column is maximum.

```
Sample Output:
Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11
Row where col1 has maximum value:
4
Row where col2 has maximum value:
3
Row where col3 has maximum value:
2
```

In [ ]:
import pandas as pd

# Sample data dict
data = {'col1': [1, 2, 3, 4, 7], 'col2': [4, 5, 6, 9, 5], 'col3': [7, 8, 12, 1, 11]}

# Create DataFrame
df = pd.DataFrame(data)

# Print original DataFrame
print(f"Original DataFrame:\n{df}\n")

# Find the row for where each column has its maximum value and print its index
print(f"Row where col1 has maximum value:\n{df['col1'].idxmax()}\n") # df['col1'].idxmax() finds the index of the maximum value in 'col1'.
print(f"Row where col2 has maximum value:\n{df['col2'].idxmax()}\n")
print(f"Row where col3 has maximum value:\n{df['col3'].idxmax()}\n")

Original DataFrame:
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11

Row where col1 has maximum value:
4

Row where col2 has maximum value:
3

Row where col3 has maximum value:
2



##25. Write a Pandas program to get the datatypes of columns of a DataFrame.

```
Sample data:
Original DataFrame:
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
.......
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0
Data types of the columns of the said DataFrame:
attempts      int64
name         object
qualify      object
score       float64
dtype: object
```

In [ ]:
import pandas as pd
import numpy as np
#Sample dictionary data
exam_data = {'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19]
}

# Create DataFrame
df = pd.DataFrame(data = exam_data)
# 'data = exam_data' This specifies the dictionary exam_data as the data to populate the DataFrame columns.

# print Original DataFrame
print(f"Original DataFrame\n{df}\n")

# get the datatypes of columns of a DataFrame
print(f"Data types of the columns of the said DataFrame:\n{df.dtypes}")


Original DataFrame
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
3         3      James      no    NaN
4         2      Emily      no    9.0
5         3    Michael     yes   20.0
6         1    Matthew     yes   14.5
7         1      Laura      no    NaN
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0

Data types of the columns of the said DataFrame:
attempts      int64
name         object
qualify      object
score       float64
dtype: object


##26. Write a Pandas program to group by the first column and get second column as lists in rows.

```
Sample data:
Original DataFrame
col1 col2
0 C1 1
1 C1 2
2 C2 3
3 C2 3
4 C2 4
5 C3 6
6 C2 5


Group on the col1:
col1
C1 [1, 2]
C2 [3, 3, 4, 5]
C3 [6]
Name: col2, dtype: object
```

In [ ]:
import pandas as pd

# Sample data
data = {'col1': ['C1', 'C1', 'C2', 'C2', 'C2', 'C3', 'C2'], 'col2': [1, 2, 3, 3, 4, 6, 5]}

# Create DataFrame
df = pd.DataFrame(data)

# Print original DataFrame
print(f"Original DataFrame\n{df}\n")

# Group by 'col1' and get 'col2' as lists in rows
gpd_df = df.groupby('col1')['col2'].apply(list)  # df.groupby('category')['values'].apply(list)
# df.groupby('col1') creates a groupby object where each unique value in 'col1' forms a group.
# ['col2'] then selects the 'col2' column from each group.
#.apply(list) is applied to each group of 'values'.It converts each group (which is a Series of numbers) into a list.

# Print grouped DataFrame
print(f"Group on the col1:\n{gpd_df}")




Original DataFrame
  col1  col2
0   C1     1
1   C1     2
2   C2     3
3   C2     3
4   C2     4
5   C3     6
6   C2     5

Group on the col1:
col1
C1          [1, 2]
C2    [3, 3, 4, 5]
C3             [6]
Name: col2, dtype: object


##27  Write a Pandas program to count number of columns of a DataFrame.

```
Sample Output:
Original DataFrame
  col1 col2 col3
0  1    4   7
1  2    5   8
2  3    6   12
3  4    9   1
4  7    5   11

Number of columns:
3
```

In [ ]:
import pandas as pd

# Sample data
data = {'col1': [1, 2, 3, 4, 7], 'col2': [4, 5, 6, 9, 5], 'col3': [7, 8, 12, 1, 11]}

# Create DataFrame
df = pd.DataFrame(data)

# print Original DataFrame
print(f"Original DataFrame\n{df}\n")

#df.shape returns a tuple (number of row , number of column) so df.shape[1] returns the second element in the tuple which is  number of column
print(f"Number of columns:\n{df.shape[1]}")

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11

Number of columns:
3


##28.  Write a Pandas program to get first n records of a DataFrame.

```
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11

First 3 rows of the said DataFrame':
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
```


In [ ]:
import pandas as pd

# Sample data
data = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1, 11]}

# Create DataFrame
df = pd.DataFrame(data)

# print Original DataFrame
print(f"Original DataFrame\n{df}\n")

# get first 3 records of a DataFrame.
print(f"First 3 rows of the said DataFrame':\n{df.head(3)}\n")

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

First 3 rows of the said DataFrame':
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8



##29. Write a Pandas program to get last n records of a DataFrame.

```
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11

Last 3 rows of the said DataFrame':
col1 col2 col3
3 4 9 12
4 7 5 1
5 11 0 11
```

In [ ]:
import pandas as pd

# Sample data
data = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1, 11]}

# Create DataFrame
df = pd.DataFrame(data)

# print Original DataFrame
print(f"Original DataFrame\n{df}\n")

# get last 3 records of a DataFrame.
print(f"Last 3 rows of the said DataFrame':\n{df.tail(3)}\n")

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

Last 3 rows of the said DataFrame':
   col1  col2  col3
3     4     9    12
4     7     5     1
5    11     0    11



##30.  Write a Pandas program to get topmost n records within each group of a DataFrame.

```
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11

```
```
topmost n records within each group of a DataFrame:
col1 col2 col3
5 11 0 11
4 7 5 1
3 4 9 12
col1 col2 col3
3 4 9 12
2 3 6 8
1 2 5 5
4 7 5 1
col1 col2 col3
3 4 9 12
5 11 0 11
2 3 6 8
```

In [ ]:
import pandas as pd

# Sample data
data = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1, 11]}

# Create DataFrame
df = pd.DataFrame(data)

print(f"Original DataFrame\n{df}\n")

# Function to get top n records within each group
def get_top_n_records(df, sort_col, n=3):
    return df.sort_values(by=sort_col, ascending=False).head(n)

print("topmost n records within each group of a DataFrame:")

print(f"{get_top_n_records(df, 'col1', n=3)}\n")

print(f"{get_top_n_records(df, 'col2', n=4)}\n")

print(f"{get_top_n_records(df, 'col3', n=3)}\n")


Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

topmost n records within each group of a DataFrame:
   col1  col2  col3
5    11     0    11
4     7     5     1
3     4     9    12

   col1  col2  col3
3     4     9    12
2     3     6     8
1     2     5     5
4     7     5     1

   col1  col2  col3
3     4     9    12
5    11     0    11
2     3     6     8



##31. Write a Pandas program to add a prefix or suffix to all columns of a given DataFrame.

```
Sample Output:
Original DataFrame
W X Y Z
0 68 78 84 86
1 75 85 94 97
2 86 96 89 96
3 80 80 83 72
4 66 86 86 83

Add prefix:
A_W A_X A_Y A_Z
0 68 78 84 86
1 75 85 94 97
2 86 96 89 96
3 80 80 83 72
4 66 86 86 83

Add suffix:
W_1 X_1 Y_1 Z_1
0 68 78 84 86
1 75 85 94 97
2 86 96 89 96
3 80 80 83 72
4 66 86 86 83

```

In [ ]:
import pandas as pd

# Sample data
data = {'W': [68, 75, 86, 80, 66], 'X': [78, 85, 96, 80, 86], 'Y': [84, 94, 89, 83, 86], 'Z': [86, 97, 96, 72, 83]}

# Create the DataFrame
df = pd.DataFrame(data)

# Print original DataFrame
print(f"Original DataFrame\n{df}\n")

# Add prefix using add_prefix method
prefixed_df = df.add_prefix('A_')

# print DataFrame with prefix added
print(f"Add prefix:\n{prefixed_df}")

# Add suffix using add_suffix method
suffixed_df = df.add_suffix('_1')

# Print DataFrame with suffix added
print(f"Add suffix:\n{suffixed_df}")


Original DataFrame
    W   X   Y   Z
0  68  78  84  86
1  75  85  94  97
2  86  96  89  96
3  80  80  83  72
4  66  86  86  83

Add prefix:
   A_W  A_X  A_Y  A_Z
0   68   78   84   86
1   75   85   94   97
2   86   96   89   96
3   80   80   83   72
4   66   86   86   83
Add suffix:
   W_1  X_1  Y_1  Z_1
0   68   78   84   86
1   75   85   94   97
2   86   96   89   96
3   80   80   83   72
4   66   86   86   83


##32. Write a Pandas program to convert continuous values of a column in a given DataFrame to categorical.
```
Input:
 'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Syed Wharton', 'Kierra Gentry'],
      'age': [18, 22, 85, 50, 80, 5]


Output:
Age group:
0 kids
1 adult
2 elderly
3 adult
4 elderly
5 kids
Name: age_groups, dtype: category
Categories (3, object): [kids < adult < elderly]
```

In [8]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Syed Wharton', 'Kierra Gentry'],
    'Age': [18, 22, 85, 50, 80, 5]
}

# Create DataFrame
df = pd.DataFrame(data)
#print(df)

# Define bins and labels for age groups
bins = [0, 19, 60, 120]  # Bins for kids, adult, elderly

# Ages from 0 up to (but not including) 19 are categorized as 'kids'.
# Ages from 19 up to (but not including) 60 are categorized as 'adult'.
# Ages from 60 up to (but not including) 120 are categorized as 'elderly'.
# Any age outside these ranges would not fall into any of these categories based on the given bins.

labels = ['kids', 'adult', 'elderly'] # labels for the age group

# Convert 'Age' column to categorical 'age_groups'
df['age_groups'] = pd.cut(df['Age'], bins=bins, labels=labels, right=False)


#df[['Name', 'Age', 'age_groups']]

print(f"Age group:\n{df['age_groups']}")

Age group:
0       kids
1      adult
2    elderly
3      adult
4    elderly
5       kids
Name: age_groups, dtype: category
Categories (3, object): ['kids' < 'adult' < 'elderly']


##33. Write a Pandas program to append rows to an existing DataFrame and display the combined data.

```
Test Data:
student_data1
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199


New Row(s)
student_id                  S6
name          Scarlette Fisher
marks                      205
dtype: object
```

In [ ]:
import pandas as pd

# DataFrame
student_data1 = pd.DataFrame({
    'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
    'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'],
    'marks': [200, 210, 190, 222, 199]
})

print(f"Test Data:\nstudent_data1\n{student_data1}\n\n")

# New Row as a pd Series
new_row = pd.Series(['S6', 'Scarlette Fisher', 205], index=['student_id', 'name', 'marks'])

print(f"New Row(s)\n{new_row}\n\n")


# Append the new row to the existing DataFrame using concat
student_data1 = pd.concat([student_data1, new_row.to_frame().T], ignore_index=True)

#new_row is a pandas Series containing data for a new row that we want to append to the student_data1 DataFrame.
#.to_frame() converts the Series new_row into a DataFrame. The resulting DataFrame has a single row with column names derived from the index of the Series.
#.T transposes (flips) the DataFrame, making the row into a column. This step ensures that the new row is added as a single row DataFrame with columns aligned properly.

#print(f"new_row.to_frame()\n{new_row.to_frame()}")
#print(f"new_row.to_frame().T\n{new_row.to_frame().T}")

# print the combined data
print(f"Combined DataFrame:\n{student_data1}")


Test Data:
student_data1
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199


New Row(s)
student_id                  S6
name          Scarlette Fisher
marks                      205
dtype: object


Combined DataFrame:
  student_id              name marks
0         S1  Danniella Fenton   200
1         S2      Ryder Storey   210
2         S3      Bryce Jensen   190
3         S4         Ed Bernal   222
4         S5       Kwame Morin   199
5         S6  Scarlette Fisher   205


##34  Write a Pandas program to join the two given dataframes along rows and merge with another dataframe along the common column id.

```
Test Data:
student_data1:
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
student_data2:
  student_id              name  marks
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201
```
```

exam_data:
   student_id  exam_id
0          S1       23
1          S2       45
2          S3       12
3          S4       67
4          S5       21
5          S7       55
6          S8       33
7          S9       14
8         S10       56
9         S11       83
10        S12       88
11        S13       12
```


In [ ]:
import pandas as pd

# Data frames
student_data1 = pd.DataFrame({
    'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
    'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'],
    'marks': [200, 210, 190, 222, 199]
})

student_data2 = pd.DataFrame({
    'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
    'name': ['Scarlette Fisher', 'Carla Williamson', 'Dante Morse', 'Kaiser William', 'Madeeha Preston'],
    'marks': [201, 200, 198, 219, 201]
})


exam_data = pd.DataFrame({
    'student_id': ['S1', 'S2', 'S3', 'S4', 'S5', 'S7', 'S8', 'S9', 'S10', 'S11', 'S12', 'S13'],
    'exam_id': [23, 45, 12, 67, 21, 55, 33, 14, 56, 83, 88, 12]
})

# join the two given dataframes along rows
dataframes_joined = pd.concat([student_data1, student_data2], ignore_index=True)

# merge with another dataframe along the common column id 'student_id'. and print the output
print(pd.merge(dataframes_joined, exam_data, on='student_id'))





  student_id              name  marks  exam_id
0         S1  Danniella Fenton    200       23
1         S2      Ryder Storey    210       45
2         S3      Bryce Jensen    190       12
3         S4         Ed Bernal    222       67
4         S4  Scarlette Fisher    201       67
5         S5       Kwame Morin    199       21
6         S5  Carla Williamson    200       21
7         S7    Kaiser William    219       55
8         S8   Madeeha Preston    201       33
